### ISSUE TITLE
Poprawa controllera dla tras 

### ISSUE THREAD

**Issue by zaquncio** [edk-software/my-api#1]
project id dla wyciągania url, oraz approved - route list

**Comment by Wariorek** [comment]
do routelisty dodany parametr projectId oraz approved:
routeList?editionId=2018&approved=0&projectId=3
commit z #1

**Comment by zaquncio** [comment]
Ta zmiana jest bez sensu po co wyciągać trasy nie zatwierdzone, project id to to samo co edition id więc całe zmiany są do cofnięcia. 
Powinno zostać tylko `conditions.push(" r.approved=1");` dla getEdkRouteList.
Project id brakuje dla wyciągania linku do śladu: getEdkRoute `from cantiga_project_settings where `key` = 'edk_mirror_url`'

**Comment by zaquncio** [comment]
trzeba usunąć te informacje z requesta, a dodać do warunków zapytania j.w.

**Comment by Wariorek** [comment]
chodzi o pliki ze śladem, że je trzeba po editionId wyciagac(projectId)
" if(r.mapFile is not null, concat_ws('/', (select `value` from cantiga_project_settings where `key` = 'edk_mirror_url'),r.publicAccessSlug, CONCAT('edk-map-route-',r.id, '.', SUBSTRING_INDEX(r.mapFile,'.',-1))) , null) as mapLink, " +
            " if(r.gpsTrackFile is not null, concat_ws('/', (select `value` from cantiga_project_settings where `key` = 'edk_mirror_url'),r.publicAccessSlug, CONCAT('edk-gps-route-',r.id, '.', SUBSTRING_INDEX(r.gpsTrackFile,'.',-1))), null) as gpsLink," +
            " if(r.descriptionFile is not null ,concat_ws('/', (select `value` from cantiga_project_settings where `key` = 'edk_mirror_url'),r.publicAccessSlug, CONCAT('edk-guide-route-',r.id, '.', SUBSTRING_INDEX(r.descriptionFile,'.',-1))), null) as DescriptionLink," +

???

**Comment by Wariorek** [comment]
widze ze poprawiles juz w kodzie, temat do zamkniecia?

**Comment by Wariorek** [comment]
edkRoute List zawsze ma dodane approved = 1
