### ISSUE TITLE
Trasy z poprzednich edycji EDK widoczne na stronie www

### ISSUE THREAD

**Issue by quchasz** [edk-software/my-api#2]
Trasy edycji 2019 mają **id>=1688**

Istnieje możliwość wyświetlenia starych tras po ręcznym wpisaniu id w adres (lub poprzez linka zachowanego w roku ubiegłym), np:
https://www.edk.org.pl/trasa-edk/831
https://www.edk.org.pl/trasa-edk/845

Dla takiej trasy na mapie nie widać śladu (*dobrze*), nie można się również na nią zarejestrować (*to też dobrze*), jednak uczestnicy mogą mieć wątpliwości co do tras, ponieważ wygląda to jak trasa aktualna (przykład dla trasy 845):

![Screen Shot 2019-03-12 at 14 16 12](https://user-images.githubusercontent.com/47346557/54203140-e86fb780-44d1-11e9-8dab-9fdda83b6f14.png)

Jakimś szczególnym przypadkiem jest trasa id=2420 która była w edycji 2018, jednak miała zatwierdzenie z `5 marca 2019 15:23 przez Artur Apryjas` (na szczęście nie była widoczna wśród tras tegorocznej edycji) -> zdjąłem zatwierdzenie trasy.
![Screen Shot 2019-03-12 at 14 27 22](https://user-images.githubusercontent.com/47346557/54204105-dc84f500-44d3-11e9-929b-2f7f7ef1a030.png)

**Comment by Wariorek** [comment]
Dla poniższego endpointa pobieramy tylko trasy z archived = 0
routes?id=807&editionId=2018
