### ISSUE TITLE
Strona www wyświetla niezatwierdzone trasy

### ISSUE THREAD

**Issue by quchasz** [edk-software/my-api#3]
Istnieje możliwość zobaczenia na stronie edk.org.pl trasy która nie jest zatwierdzona (również z rejonu który nie jest aktywny) - wystarczy w przeglądarce w polu adres wpisać id takiej trasy, np. jedna z tras rejony testowego:
https://www.edk.org.pl/trasa-edk/2256

Problem znaleziony przez niecierpliwego lidera, który nie może się doczekać publikacji swojego rejonu na stronie www.

**Comment by zaquncio** [comment]
Do poprawy metoda pobierania wszystkich tras. Dodać warunek status trasy active=1

**Comment by Wariorek** [comment]
czy nie chodzi o pole approved? Jeśli tak to jest to zmienione w Poprawa controllera dla tras #1
(mozna wybrac approved przez parametr, jesli nie ma parametru w url to domyslnie approved = 1)

**Comment by zaquncio** [comment]
Jedna sprawa to jest approved, a druga to status rejonu `cantiga_areas_statuses`  chyba kolumna `publication`, albo `active`

**Comment by Wariorek** [comment]
https://user-images.githubusercontent.com/7151417/55278458-d2a12580-530c-11e9-9881-8c5ea65e86cf.png

Może chodziło Ci o kolumnę isPublish, tyle że to już jest dodane, chodziło Ci o coś innego czy temat do zamknięcia?
